name: Workflow 1
on:
  pull_request:
    branches: [branch-github-test-2]

jobs:
  teste:
    runs-on: macOS-latest
    
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build and Test
        run: |
          xcodebuild clean test -project FutList.xcodeproj -scheme FutList -destination "${destination}"
        env: 
          destination: ${{ matrix.destination }}
